from building import *
import os

cwd     = GetCurrentDir()
path = [cwd]
src  = []



if GetDepend(['BSP_USING_IMU']):
    path += [cwd + '/imu']


if GetDepend(['BSP_USING_ADIS16467']):
    src += [cwd + '/imu/ADIS16467/adis16467.c']
    path += [cwd + '/imu/ADIS16467']

if GetDepend(['BSP_USING_DWT']):
    src += [cwd + '/dwt/drv_dwt.c']
    path += [cwd + '/dwt']

if GetDepend(['BSP_USING_PS_MSG']):
    src += [cwd + '/msg/drv_msg.c']
    path += [cwd + '/msg']

src  += [cwd + '/usr_callback.c']

group = DefineGroup('RM_Modules', src, depend = [''], CPPPATH = path)

Return('group')
