from building import *
import os

cwd     = GetCurrentDir()

src = [cwd + '/robot.c']

path = [cwd]



if GetDepend(['BSP_USING_INS_TASK']):
    src += Glob(cwd + '/ins/*.c')
    path += [cwd + '/ins']

if GetDepend(['BSP_USING_TRANSMMISION_TASK']):
    src += Glob(cwd + '/transmission/*.c')
    path += [cwd + '/transmission']

group = DefineGroup('RM_Task', src, depend = [''], CPPPATH = path)

Return('group')
